### ISSUE TITLE
Out of memory error

### ISSUE THREAD

**Issue by stefanmf** [awentzonline/image-analogies#10]
I'm getting an "Error allocating 45158400 bytes of device memory (out of memory). Driver report 44666880 bytes free and 536543232 bytes total" running the example, at iteration 1x0. Maybe 512mb video memory is simply too little?

**Comment by awentzonline** [comment]
Yeah that's probably too little, sorry! For what it's worth, I'm trying to get the TensorFlow backend working which should make it feasible for people to run on the CPU with their (probably) much larger system memory.
