### ISSUE TITLE
Support for Leaf (Tensorflow alternative)

### ISSUE THREAD

**Issue by giovannibonetti** [awentzonline/image-analogies#23]
Leaf is an alternative to Tensorflow that is allegedly faster and easier to run in the GPU, thanks to the Rust language capabilities. Torch, on the other hand, is powered by LuaJIT, and seems great, too.

Torch seems very fast, too - http://autumnai.com/deep-learning-benchmarks

Do you think it would be interesting to support any of them?
https://github.com/autumnai/leaf
https://github.com/torch/torch7

**Comment by awentzonline** [comment]
For torch I think it might be somewhat straightforward to add this to https://github.com/chuanli11/CNNMRF since this is essentially that algorithm plus some extra setup for the content loss. That's actually not too bad of an idea since that project has some nice features.

**Comment by dmr** [comment]
Did you integrate it yet?

**Comment by awentzonline** [comment]
Looks like cool stuff but I'm not going to be rewriting this project in rust or lua any time soon.
