### ISSUE TITLE
Model weights not found (see "--vgg-weights" parameter).

### ISSUE THREAD

**Issue by r0fls** [awentzonline/image-analogies#30]
It says weights are optional in the README. Is that a documentation error, or is this a bug?

Thanks

**Comment by albinoz** [comment]
Hi, You must be in exemples path to be found.
Exemple if image analogies is in Picture on Mac OS X:
source ~/Pictures/image-analogies/venv/bin/activate ; cd ~/Pictures/image-analogies/examples

**Comment by awentzonline** [comment]
The weights are required. What's optional is how you specify the location.
