### ISSUE TITLE
SyntaxError: Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by Heipiao** [awentzonline/image-analogies#32]
try to run example,
`make_image_analogy.py images/arch-mask.jpg images/arch.jpg images/arch-newmask.jpg out/arch`
the output is SyntaxError: Missing parentheses in call to 'print'
(venv) liudeMacBook-Pro:scripts liu$ make_image_analogy.py images/arch-mask.jpg images/arch.jpg images/arch-newmask.jpg out/arch
Using Theano backend.
/Users/liu/Code/venv/lib/python3.4/site-packages/theano/tensor/signal/downsample.py:6: UserWarning: downsample module has been moved to the theano.tensor.signal.pool module.
  "downsample module has been moved to the theano.tensor.signal.pool module.")
Theano CPU mode detected. Forcing a-scale-mode to "match"
Using PatchMatch model
Traceback (most recent call last):
  File "/Users/liu/Code/venv/bin/make_image_analogy.py", line 21, in <module>
    from image_analogy.models.nnf import NNFModel as model_class
  File "/Users/liu/Code/venv/lib/python3.4/site-packages/image_analogy/models/nnf.py", line 7, in <module>
    from image_analogy.losses.nnf import nnf_analogy_loss, NNFState, PatchMatcher
  File "/Users/liu/Code/venv/lib/python3.4/site-packages/image_analogy/losses/nnf.py", line 5, in <module>
    from .patch_matcher import PatchMatcher
  File "/Users/liu/Code/venv/lib/python3.4/site-packages/image_analogy/losses/patch_matcher.py", line 187
    print "[congrid] dimensions error. " \
                                       ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by imdark** [comment]
that is a difference between different version of python, python 3.x requires print() while the the old python 2.x did not require it.

**Comment by awentzonline** [comment]
Fixed, thanks for reporting!
