### ISSUE TITLE
Reduce memory requirements

### ISSUE THREAD

**Issue by awentzonline** [awentzonline/image-analogies#5]
Maybe adapt the approach taken in https://github.com/chuanli11/CNNMRF

**Comment by alexjc** [comment]
In Torch you can get full control over the forward and backward passes, and Chuan Li's code basically streams patches from main memory to GPU in the middle of the computation before propagating the error back.

If you use `T.grad()` Theano by default doesn't let you control memory like this in Torch, so I'm very curious how you'd approach this without throwing away the benefits/approach of Theano completely. Maybe I'm missing a magic "stream from main memory" operator or something ;-)

**Comment by awentzonline** [comment]
THEANO_FLAGS="use_much_less_memory_please=true"

Seriously though, I'm not quite sure what to do about this yet.
