### ISSUE TITLE
not working as well as it did a few days ago?

### ISSUE THREAD

**Issue by memo** [awentzonline/image-analogies#9]
Hey, great wrk on this. looks great. However the changes you've made in the past few days have changed the output quite a lot. A few days ago (commit: https://github.com/awentzonline/image-analogies/commit/c6f35e73bfb35035e195dd5a3bb5a018588bec3e ) I would get this (which looks perfect):
![pf0000_at_iteration_2_4_old](https://cloud.githubusercontent.com/assets/144230/13566824/761e7314-e44f-11e5-8bed-ac9900ddc970.png)

but now I get this (with the same settings):
![pf0000_at_iteration_2_4_new](https://cloud.githubusercontent.com/assets/144230/13566828/7cc15bf0-e44f-11e5-85aa-03348d6af954.png)

my mask is this:
![pf-nm_0000](https://cloud.githubusercontent.com/assets/144230/13566855/93846774-e44f-11e5-8a3c-f526af135847.png)

(also new version is exactly 2x faster, which is great. but I'm not anywhere near the same results)

**Comment by awentzonline** [comment]
Two things have changed that might affect that: 
 * The analogy weight should be set a lot higher than the MRF weight (it's 9:1 by default, now) that should fill up the hole in your sexy sax man.
 * I added an option for stretch contrast you can turn it off with --contrast=0  I should probably turn it down a little more by default.

Great work on this: https://twitter.com/memotv/status/706817101386936320

**Comment by awentzonline** [comment]
Another option I recently added that you might want to check out is `--pool-mode`. It's set to max pooling by default but average pooling sometimes looks nicer `--pool-mode=avg` for natural images.

**Comment by memo** [comment]
ok, interestingly I need to make analogy weight about 20 to get results similar to the version from 2 days ago (even 16 doesn't cut it). Is it possible that there is a factor of 2x introduced somewhere since that commit? contrast and avg pooling did affect the image a little bit, but doesn't really affect the sexy sax man. 

analogy weight: 16 (see little hole in his belly)
![pf0000_at_iteration_2_4 --contrast 0 --pool-mode avg --analogy-w 16 576s](https://cloud.githubusercontent.com/assets/144230/13580416/18a480ca-e49a-11e5-9ef9-e36c03e0e2a5.png)

analogy weight: 20
![pf0000_at_iteration_2_4 --contrast 0 --pool-mode avg --analogy-w 20 576s](https://cloud.githubusercontent.com/assets/144230/13580428/1eb2f2da-e49a-11e5-8f1b-552e48fc65d1.png)

**Comment by awentzonline** [comment]
Would you send me your source images so I can fool around with them? Also, what do your settings look like?

**Comment by memo** [comment]
I've tried contrast=0, --pool-mode=avg, --analogy-w=9, 16, 20 (which are the images above), rest is default. I'm happy with the results I got in the above post with analogy-weight=20, i was just curious why I had to use 20 with this version to get similar results as 9 before. 

original and mask below. dim 256x163, i'm now trying at 1024x654 (taking a while!)
![pf-m](https://cloud.githubusercontent.com/assets/144230/13582294/80bd4f58-e4a3-11e5-9d26-26fe0ae997e0.png)
![pf-o](https://cloud.githubusercontent.com/assets/144230/13582295/80be4f84-e4a3-11e5-8a1d-011fd3aebcf4.png)

**Comment by awentzonline** [comment]
Thanks! I'm guessing there's something I'm not normalizing properly, since I usually generate larger images around 2x as big and use 1/2 the analogy loss.

**Comment by awentzonline** [comment]
Ok I've tracked down a few bugs and this should all be a little nicer. Now the mrf/analogy-w both start at 1.0. For your sexy sax man I found that lowering mrf to 0.5  reproduced him without the hole. Also, given the size, it looks good with `--mrf-w=0` which also allows it to render faster. The gains aren't as evident at this size with one image, but if you're doing a bunch of frames then maybe it adds up.

![sexysax_at_iteration_2_4](https://cloud.githubusercontent.com/assets/5231065/13640296/a569efa0-e5d9-11e5-8fb6-3acdd0dc0986.png)

**Comment by memo** [comment]
cool thx, just had a quick look, seems about right.

**Comment by neelkadia-zz** [comment]
This is a great tool Indeed! buy Guys, Why I'm having result like this!

I'm running this by `contrast=0 --pool-mode=avg, --analogy-w=9 --patch-size=3`

![arch_at_iteration_2_4](https://user-images.githubusercontent.com/1472233/29966750-e9c9996e-8f30-11e7-9532-e40b0cafd0c6.png)
